### ISSUE TITLE
Project Borg (Kubernetes)

### ISSUE THREAD

**Issue by andrewdalpino** [RubixML/Server#11]
This ticket is to determine if Rubix Server can be used with Kubernetes to deploy and autoscale instances.

In the process we should ...

A. Determine if we need to make any changes to the library to either make it work or make it easier to work
B. Create a container for other developers to use
C. Produce documentation for the procedure to be added to the README

Related Reading:

- https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/44843.pdf

**Comment by torchello** [comment]
@andrewdalpino I am on it.
